site_name: Haynes Cigar Journal
site_url: https://hayneslab.net/cigar-journal/
site_author: Tom Haynes

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - navigation.tabs
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
        
# Plugins
plugins:
  - search

# Hooks
## Add 'hooks:' here

# Additional configuration
## Add 'extra:' block here

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home:
    - index.md
    - Purchase History: purchase-history.md
    - Cheat Sheet: cheat-sheet.md
    - About the Author: about-the-author.md
  - NC Reviews:
    - nc-reviews/index.md
    - Davidoff:
      - nc-reviews/davidoff/index.md
      - Winston Churchill The Late Hour: nc-reviews/davidoff/winston-churchill-the-late-hour.md
      - Signature: nc-reviews/davidoff/signature.md
      - Millennium: nc-reviews/davidoff/millennium.md
      - Yamasa: nc-reviews/davidoff/yamasa.md
      - Grand Cru: nc-reviews/davidoff/grand-cru.md
      - Nicaragua: nc-reviews/davidoff/nicaragua.md
      - Escurio: nc-reviews/davidoff/escurio.md
      - Winston Churchill: nc-reviews/davidoff/winston-churchill.md
    - Padron:
      - nc-reviews/padron/index.md
      - 1964 Natural: nc-reviews/padron/1964-natural.md
      - 1964 Maduro: nc-reviews/padron/1964-maduro.md
      - 1926 Natural: nc-reviews/padron/1926-natural.md
      - 1926 Maduro: nc-reviews/padron/1926-maduro.md
      - 3000 Maduro: nc-reviews/padron/3000-maduro.md
    - Drew Estate:
      - nc-reviews/drew-estate/index.md
      - Undercrown 10: nc-reviews/drew-estate/undercrown-10.md
      - Liga Privada Anniversario: nc-reviews/drew-estate/liga-privada-anniversario.md
      - Liga Privada T52: nc-reviews/drew-estate/liga-privada-t52.md
      - Liga Privada No. 9: nc-reviews/drew-estate/liga-privada-no-9.md
    - Oliva:
      - nc-reviews/oliva/index.md
      - Series V Melanio Maduro: nc-reviews/oliva/series-v-melanio-maduro.md
    - Caldwell:
      - nc-reviews/caldwell/index.md
      - The King Is Dead: nc-reviews/caldwell/the-king-is-dead.md
    - My Father:
      - nc-reviews/my-father/index.md
      - Le Bijou 1922: nc-reviews/my-father/le-bijou-1922.md
    - Arturo Fuente:
      - nc-reviews/arturo-fuente/index.md
      - OpusX Lost City: nc-reviews/arturo-fuente/opusx-lost-city.md
    - La Flor Dominicana:
      - nc-reviews/la-flor-dominicana/index.md
      - La Nox: nc-reviews/la-flor-dominicana/la-nox.md
    - God of Fire:
      - nc-reviews/god-of-fire/index.md
      - Series B 11/16: nc-reviews/god-of-fire/series-b-11-16.md
  - CC Reviews:
    - cc-reviews/index.md
    - Romeo y Julieta:
      - cc-reviews/romeo-y-julieta/index.md
      - Wide Churchill: cc-reviews/romeo-y-julieta/wide-churchill.md
      - No 2 Tubo: cc-reviews/romeo-y-julieta/no-2-tubo.md
    - Montecristo:
      - cc-reviews/montecristo/index.md
      - Double Edmundo: cc-reviews/montecristo/double-edmundo.md
      - No 2: cc-reviews/montecristo/no-2.md
    - Hoyo De Monterrey:
      - cc-reviews/hoyo-de-monterrey/index.md
      - Le Hoyo du Depute: cc-reviews/hoyo-de-monterrey/le-hoyo-du-depute.md
    - Ramon Allones:
      - cc-reviews/ramon-allones/index.md
      - Specially Selected: cc-reviews/ramon-allones/specially-selected.md
      - No 3: cc-reviews/ramon-allones/no-3.md
    - Quai d'Orsay:
      - cc-reviews/quai-dorsay/index.md
      - No 54: cc-reviews/quai-dorsay/no-54.md
    - Rafael Gonzales:
      - cc-reviews/rafael-gonzales/index.md
      - Perla: cc-reviews/rafael-gonzales/perla.md
    - H Upmann:
      - cc-reviews/h-upmann/index.md
      - Coronas Major Tubo: cc-reviews/h-upmann/coronas-major-tubo.md
    - Partagas:
      - cc-reviews/partagas/index.md
      - Serie D No 4: cc-reviews/partagas/serie-d-no-4.md